import { useNavigate } from 'react-router-dom';
import { ArrowLeft, MessageCircleHeart } from 'lucide-react';
import { Button } from '@/components/ui/button';

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="space-y-3">
    <h2 className="text-lg font-bold">{title}</h2>
    <div className="text-sm text-muted-foreground leading-relaxed space-y-2">{children}</div>
  </div>
);

const TermsPage = () => {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-background">
      <nav className="sticky top-0 z-50 bg-background/80 backdrop-blur-xl border-b border-border/20 px-4 h-14 flex items-center gap-3">
        <Button variant="ghost" size="icon" onClick={() => navigate(-1)} className="-ml-2">
          <ArrowLeft className="w-5 h-5" />
        </Button>
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-md gradient-primary flex items-center justify-center">
            <MessageCircleHeart className="w-3 h-3 text-primary-foreground" />
          </div>
          <span className="font-bold text-sm">Partner<span className="gradient-text">AI</span></span>
        </div>
      </nav>

      <div className="max-w-2xl mx-auto px-4 py-12 space-y-10">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated: February 2026</p>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>By accessing or using PartnerAI ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service. These Terms are governed by the laws of India.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>PartnerAI is an AI-powered chat simulation service that allows users to upload WhatsApp chat exports and interact with an AI that mimics the conversational style of their chat partner. The Service is provided for entertainment and personal use only.</p>
        </Section>

        <Section title="3. Eligibility">
          <p>You must be at least 18 years of age to use this Service. By using PartnerAI, you represent and warrant that you are 18 or older and have the legal capacity to enter into these Terms.</p>
        </Section>

        <Section title="4. User Accounts">
          <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately of any unauthorized use at support@partnerai.app. We reserve the right to terminate accounts that violate these Terms.</p>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree NOT to: upload chat data belonging to third parties without their explicit consent; use the Service for any illegal, harmful, or fraudulent purpose; attempt to reverse-engineer, scrape, or misuse the AI models; upload content involving minors; impersonate any person or entity; or circumvent usage limits through technical means.</p>
        </Section>

        <Section title="6. Intellectual Property">
          <p>The Service, its original content, features, and functionality are owned by PartnerAI and are protected by Indian and international copyright laws. You retain ownership of the chat data you upload. By uploading, you grant us a limited license to process it solely to provide the Service.</p>
        </Section>

        <Section title="7. Subscriptions & Payments">
          <p>PartnerAI offers a Free plan and a Pro plan. Pro subscriptions are billed via Razorpay. All prices are displayed in INR or USD as selected. Subscription fees are non-refundable except as described in our Refund Policy.</p>
          <p>We reserve the right to modify pricing with 30 days' advance notice. Continued use after a price change constitutes acceptance.</p>
        </Section>

        <Section title="8. Disclaimer of Warranties">
          <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. We do not warrant that: the AI responses will be accurate or suitable; the Service will be uninterrupted or error-free; or the Service will meet your specific requirements.</p>
          <p>PartnerAI is an AI simulation tool. Responses are generated by AI and do not represent the actual views, thoughts, or communications of any real person.</p>
        </Section>

        <Section title="9. Limitation of Liability">
          <p>To the maximum extent permitted by applicable Indian law, PartnerAI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability to you shall not exceed the amount paid by you for the Service in the last 12 months.</p>
        </Section>

        <Section title="10. Termination">
          <p>We may terminate or suspend your account at any time, with or without notice, for violation of these Terms. Upon termination, your right to use the Service ceases immediately. You may delete your account at any time from Settings.</p>
        </Section>

        <Section title="11. Governing Law & Dispute Resolution">
          <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in India. We encourage resolving disputes amicably by contacting us at support@partnerai.app first.</p>
        </Section>

        <Section title="12. Changes to Terms">
          <p>We reserve the right to modify these Terms at any time. We will provide at least 14 days' notice for material changes. Continued use after changes constitutes acceptance of the new Terms.</p>
        </Section>

        <Section title="13. Contact">
          <p>Questions about these Terms? Email us: <a href="mailto:support@partnerai.app" className="text-primary hover:underline">support@partnerai.app</a></p>
        </Section>
      </div>

      <footer className="border-t border-border/10 py-6 text-center text-[11px] text-muted-foreground/40">
        © 2026 PartnerAI. All rights reserved.
      </footer>
    </div>
  );
};

export default TermsPage;
